#!/usr/bin/env bash

INPUT_FILE=$1
BASENAME=$(basename "$INPUT_FILE" .pdf);
OUTPUT_DIR="./tmp/$BASENAME/pdf-pages"
mkdir -p "$OUTPUT_DIR"

PAGE_COUNT=$(pdfinfo "$INPUT_FILE" | grep "Pages" | awk '{ print $2 }')

for ((CURRENT_PAGE=1;CURRENT_PAGE<PAGE_COUNT+1;CURRENT_PAGE++)); do
  echo "Extracting page $CURRENT_PAGE";
  pdftk "$INPUT" cat $CURRENT_PAGE output "$OUTPUT_DIR/page_${CURRENT_PAGE}.pdf"
done
